const productsHome = [
	{
		id: 1,
		name: 'PUMA Ultra 5 Match IT + Mid Jr',
		price: 79,
		image: 'sneakers-card-1.jpg',
		count: 1,
		stars: 4,
	},
	{
		id: 2,
		name: 'PUMA Ultra Play It Jr',
		price: 59,
		image: 'sneakers-card-2.jpg',
		count: 1,
		stars: 4,
	},
	{
		id: 3,
		name: 'Demix Quantum Vortex JR IN',
		price: 65,
		image: 'sneakers-card-3.jpg',
		count: 1,
		stars: 5,
	},
]

const productsShop = [
	{
		id: 1,
		name: 'PUMA Ultra 5 Match IT + Mid Jr',
		price: 79,
		image: 'sneakers-card-1.jpg',
		count: 1,
		stars: 4,
		text: 'The PUMA Ultra 5 Match is a secret advantage worth taking advantage of. The high-tech cleats are designed for young football players who are used to playing at full capacity. Designed for training and matches in the gym.',
	},
	{
		id: 2,
		name: 'PUMA Ultra Play It Jr',
		price: 59,
		image: 'sneakers-card-2.jpg',
		count: 1,
		stars: 4,
		text: 'With PUMA Ultra Play JR soccer cleats, your child has every chance to set new records on the field.',
	},
	{
		id: 3,
		name: 'Demix Quantum Vortex JR IN',
		price: 65,
		image: 'sneakers-card-3.jpg',
		count: 1,
		stars: 5,
		text: 'Controlling the ball and practicing techniques will be doubly pleasant with Demix Quantum Vortex JR IN futsal shoes.',
	},
	{
		id: 4,
		name: 'Womens hoodie FILA',
		price: 26,
		image: 'Hoodies-1.jpg',
		text: 'The original FILA hoodie is stylish and comfortable at the same time! The model will help you create a bright and memorable image.',
		stars: 3,
	},
	{
		id: 5,
		name: 'Longsleeve Mens Demix AeroMove Running',
		price: 19,
		image: 'Longsleeve-1.jpg',
		text: 'It is impossible to imagine a sports wardrobe without a modern technological longsleeve. Such as this running model from Demix.',
		stars: 5,
	},
	{
		id: 6,
		name: 'Longsleeve Mens Demix',
		price: 12,
		image: 'Longsleeve-2.jpg',
		text: 'Demix Longsleeve is what you need for jogging on cool days.',
		stars: 5,
	},
	{
		id: 7,
		name: 'Longsleeve Female Demix',
		price: 12,
		image: 'Longsleeve-3.jpg',
		text: 'Choose the right fitness equipment, because sports results depend on it. Demix Longsleeve is designed for productive workouts.',
		stars: 5,
	},
	{
		id: 8,
		name: 'Adidas Strutter Mens Running Shoes',
		price: 83,
		image: 'Sneakers-1.jpg',
		text: 'Adidas Strutter sneakers with a massive sole will allow you to create an original image in a sporty style. The model guarantees maximum comfort throughout the day.',
		stars: 5,
	},
	{
		id: 9,
		name: 'Mens Safety Jogger Retro Run Sneakers',
		price: 20,
		image: 'Sneakers-2.jpg',
		text: 'The versatile Safety Jogger sneakers will be a great addition to any summer look.',
		stars: 4,
	},
	{
		id: 10,
		name: 'Mens Reebok Jogger Lite Sneakers',
		price: 37,
		image: 'Sneakers-3.jpg',
		text: 'In stylish Reebok sneakers, you will stand firmly on your feet, no matter what happens during the day.',
		stars: 4,
	},
	{
		id: 11,
		name: 'Womens trousers FILA',
		price: 28,
		image: 'Trousers-1.jpg',
		text: 'FILA joggers are the perfect choice for your wardrobe. Thanks to the universal design, they will make a lot of stylish sports looks.',
		stars: 3,
	},
	{
		id: 12,
		name: 'Mens T-shirt Athlex Pulse+',
		price: 15,
		image: 'Vest-1.jpg',
		text: 'The Athlex running T-shirt will help you overcome any distance with ease and maximum comfort.',
		stars: 5,
	},
	{
		id: 13,
		name: 'Mens T-shirt Termit',
		price: 8,
		image: 'Vest-2.jpg',
		text: 'Every summer day will be truly unforgettable with a stylish T-shirt from Termit.',
		stars: 5,
	},
	{
		id: 14,
		name: 'Demix Baseline Running Mens Shorts',
		price: 12,
		image: 'Shorts-1.jpg',
		text: 'There are no small things in sports, so this model of Demix shorts takes into account everything that can help you run faster.',
		stars: 4,
	},
	{
		id: 15,
		name: 'Mens Columbia Tanner Ranch Field Jacket',
		price: 70,
		image: 'Jacket-1.jpg',
		text: 'The Columbia Tanner Ranch windbreaker is a great option for traveling and walking around the city.',
		stars: 5,
	},
]


const news = [
	{
		id: 1,
		name: 'Safonovs PSG defeated Kuzyaevs Le Havre in the first round of Ligue 1',
		image: 'news-1.jpg',
		info: 'PSG defeated Le Havre in the first round of the French Championship on a foreign field. The match ended with a score of 4:1 in favor of the Parisians. Lee Kang‑in (3), Ousmane Dembele (85), Bradley Barkola (86) and Randal Colo‑Mouani (90, from the penalty spot) scored for the visitors, Gauthier Lloris scored for the hosts (48). Russian Havre midfielder Daler Kuzyaev joined the starting line-up and spent the entire 90 minutes on the field. His compatriot, Parisian goalkeeper Matvey Safonov remained on the bench. In the second round, PSG will host Montpellier at home on August 23, and Le Havre will play away against Saint Petersburg the next day‑Etienne.',
	},
	{
		id: 2,
		name: 'Striker Alexey Makeev became an Avangard hockey player, according to the Omsk clubs website.',
		image: 'news-2.jpg',
		info: 'the announcement with the 32‑year-old striker is designed for one year. Makeev will play for Avangard at number 57. — Makeev scored a lot of points last season, he has the qualities of both a goaltender and a dispatcher. An impressive utility indicator says that this is a team player who is ready to work on any part of the site. He makes great moments, and most importantly, he has the character of a real fighter. Alexey is determined to win as much as possible, his skill and dedication will benefit the team," said Anton Kuryanov, General manager of Avangard. Makeev played for Avtomobilist Yekaterinburg last season, in 84 matches of the regular season and the KHL playoffs, he scored 42 points (20 goals + 22 assists) with a utility rating of "+19". The new FONBET season of the KHL championship starts on September 3.',
	},
	{
		id: 3,
		name: 'Team USA Men’s Basketball Wins 17th Olympic Gold Medal',
		image: 'news-3.jpg',
		info: 'Team USA Men’s Basketball won its fifth straight — and 17th overall — Olympic gold medal today in Paris in the Men’s 5x5 Basketball Final. With 12 NBA All-Stars, four NBA MVPs and six NBA League Champions on the roster, Team USA was set up for a successful run from the jump. Three-time Olympic gold medalist and Phoenix Suns forward Kevin Durant, who is Team USA’s all-time Olympic total points leader, brought the heat in the final, with 15 points, 4 assists and 4 rebounds.',
	},
	{
		id: 4,
		name: 'Skateboarder Yuto Horigome won his Second Olympic gold in Paris',
		image: 'news-4.webp',
		info: 'With a stunning final trick — a nollie 270 noseblunt slide — Nike athlete Yuto Horigome went from seventh to first place, taking home his second Olympic gold medal in Paris today. The 25-year-old Japanese skateboarder had previously won the inaugural men’s street event in his home country in 2021. Yuto has been a Nike athlete since 2016.',
	},
	{
		id: 5,
		name: 'Jakob Ingebrigtsen Brings Home Gold in the 5,000 Meter',
		image: 'news-5.webp',
		info: 'In 13:13.66 time, Nike athlete Jakob Ingebrigtsen won gold today in the 5,000-meter race. This is his second Olympic gold after winning the 1,500 meter in Tokyo in 2021. “Every part of me is about winning. Its the most important thing, and it’s what I’m going to chase,” says the Norwegian middle-distance runner. “To be able to win, you need to visualize yourself as the best. I need to see myself on top of my opponents to be able to win. When he was 16 years old, he became the youngest man in history to run a mile in less than 4 minutes. Jakob has since shattered records, including clocking two miles in under 8 minutes — a feat matched by only one other runner in the world. Now, the 23-year-old is one of the world leaders in both the mile and the 5,000 meter. Jakob attributes his success in part to his drive to compete against his two older brothers, Henrik and Filip. “When I was young, saying that I wanted to be like my brother was synonymous with saying, ‘I want to beat them,’” he says. “Weirdly, we feel like we’re part of each other’s process when we achieve some kind of success.” The three Ingebrigtsen brothers paced with Eliud Kipchoge for Breaking2. “Seeing the level of athletes who trained alongside him was crazy,” says Jakob. “At the end of the day, we all have the same goal: to see how fast human beings can go at different distances. We’re competing for that honor, but we’re also united by that competition.”',
	},
	{
		id: 6,
		name: 'Nike Debuts a Bold Color and Print for This Summer',
		image: 'news-6.jpg',
		info: 'Bringing another bold color combination to its performance footwear lineup, Nike is releasing the Electric Pack, a new colorway inspired by the brand’s storied legacy in the sport moments that take the world’s breath away. Appearing across 55 unique footwear styles, the Electric Pack colorway combines a celebrated entry in the Nike palette — the Ostrich print, the animal print introduced by Nike designer Tinker Hatfield on the Air Safari in 1987 — and Total Orange, a Nike performance color that will appear throughout the world. Caroline Abero, Sr. Director, Women’s Footwear and Apparel at Nike, served as the colorway lead for the Electric Pack. For her team, the color and print combination needed to be distinctly Nike, exuding an attitude that’s synonymous with winning: bold, fearless, irreverent. “We wanted to take something you wouldn’t think about in the context of performance — the Safari pattern — and create an artifact that signaled this new era of sport,” says Abero. “We’re bringing sport and culture together on the playing field and creating a new look of sport for the next generation.” The origin story of the Ostrich print is well known. On a jaunt through New York City’s SoHo neighborhood in the ’80s, Hatfield passed a high-end furniture boutique, where he saw a couch covered in luxurious ostrich print. Its textures were beautifully natural. Bumpy, grooved, organic. Here was an object that was elevated purely by the material it was covered in. Hatfield came back to Nike and wanted to apply the print to a performance shoe, which was wild for an era when the two worlds never mixed. Take an athletics shoe and make it …non-athletic? It was revolutionary for the time. Up until then, Nike was viewed primarily as a utilitarian performance brand. The challenge: combine lifestyle elements with a high-performance product, and then add a story through color or textures that emanates from a specific time or place. That combination stands out. And that’s the same way Nike envisions the Electric Pack standing out this summer.',
	},
]